<?php

/**
 * @file
 * Gallery link
 *
 * This module provides a field formatter for displaying images as gallery.
 */

/* We define the version of fancybox here so that it's easy to update. */
define('GALLERY_LINK_FANCYBOX_VERSION', '1.3.4');

/**
 * Implements hook_theme().
 */
function gallery_link_theme() {
  return array(
    'gallery_link' => array(
      'variables' => array('items' => array(), 'link_text' => NULL, 'style' => NULL, 'link_options' => array(), 'fancybox_options' => array()),
    ),
  );
}

/**
 * Implements hook_requirements().
 */
function gallery_link_requirements($phase) {
  $requirements = array();
  $t = get_t();

  if ($phase == 'runtime') {

    // Get path to fancybox library.
    $path = libraries_get_path('fancybox');
    // Check whether necessary css and js files are available.
    $css = file_exists($path . '/jquery.fancybox-' . GALLERY_LINK_FANCYBOX_VERSION . '.css');
    $js = file_exists($path . '/jquery.fancybox-' . GALLERY_LINK_FANCYBOX_VERSION . '.pack.js');

    // If they not available, report an error.
    if (!$css && !$js) {
      $requirements['gallery_link_fancybox'] = array(
        'title' => $t('Gallery link'),
        'value' => $t('Not Found'),
        'severity' => REQUIREMENT_ERROR,
        'description' => $t('You need to <a href="!url">download</a> fancybox @version and put the extracted fancybox folder into <code>sites/all/libraries/</code>.', array(
          '!url' => url('http://fancybox.googlecode.com/files/jquery.fancybox-' . GALLERY_LINK_FANCYBOX_VERSION . '.zip'),
          '@version' => GALLERY_LINK_FANCYBOX_VERSION,
        )),
      );
    }
  }

  return $requirements;
}

/**
 * Implements hook_field_formatter_info().
 */
function gallery_link_field_formatter_info() {
  return array(
    'gallery_link' => array(
      'label' => t('Gallery link'),
      'field types' => array('image'),
      'settings' => array(
        'style' => 'thumbnail',
        'link_text' => 'Open gallery',
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function gallery_link_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  // This gets the view mode where the settings are stored.
  $display = $instance['display'][$view_mode];
  // This gets the settings.
  $settings = $display['settings'];

  $element = array();

  // Allow to use original image.
  $styles = array('' => t('- None -'));

  // Load all image styles.
  $image_styles = image_styles();
  $styles += drupal_map_assoc(array_keys($image_styles));

  $element['style'] = array(
    '#type' => 'select',
    '#title' => t('Image style'),
    '#description' => t('Select the style of the gallery images'),
    '#default_value' => $settings['style'],
    '#options' => $styles,
  );

  $element['link_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Link text'),
    '#description' => t('This text triggers the gallery on click.'),
    '#default_value' => $settings['link_text'],
  );

  // @TODO: Add more settings like fancybox options etc.
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function gallery_link_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('Place a gallery link with %style images and the trigger text is "%link_text".', array(
    '%style' => $settings['style'],
    '%link_text' => $settings['link_text'],
      ));
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function gallery_link_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  // We store all settings in a variable.
  $settings = $display['settings'];
  // We also store the settings directly in a variable.
  $style = $settings['style'];
  $link_text = $settings['link_text'];

  $variables = array(
    'items' => $items,
    'link_text' => $link_text,
    'style' => $style,
  );

  $element[0]['#markup'] = theme('gallery_link', $variables);

  return $element;
}

/**
 * Returns a link which triggers a gallery
 *
 * @param array $variables
 *   An array which contains the field values.
 *
 *   link_text (string)
 *     This is the text of the trigger link
 *   style (string)
 *     The images will be display with this image style
 *   link_options (array)
 *     (optional) Here can you pass an array which is structured like the
 *     options from the l() function
 *   fancybox_options (array)
 *     (optional) Here you can pass an array which defines the fancybox options
 *     (http://fancybox.net/api)
 *
 * @return string
 *   A link which triggers the gallery on click
 */
function theme_gallery_link($variables) {

  // Getting all variables.
  $items = $variables['items'];
  $link_text = $variables['link_text'];
  $style = $variables['style'];
  $link_options = $variables['link_options'];
  $fancybox_options = $variables['fancybox_options'];

  // We count so that we can support multiple galleries.
  static $counter = 0;
  $data = array();
  $data['images'] = array();
  $output = '';

  foreach ($items as $delta => $item) {
    $data['images'][$delta]['href'] = ($style != '') ? image_style_url($style, $item['uri']) : file_create_url($item['uri']);

    // Store the image title.
    if (!empty($item['title'])) {
      $data['images'][$delta]['title'] = check_plain($item['title']);
    }
  }

  if (isset($fancybox_options) && $fancybox_options) {
    $data['options'] = $fancybox_options;
  }

  // We add needed files for fancybox and our custom javascript file.
  drupal_add_css(libraries_get_path('fancybox') . '/jquery.fancybox-' . GALLERY_LINK_FANCYBOX_VERSION . '.css');
  drupal_add_css(drupal_get_path('module', 'gallery_link') . '/gallery_link.css');
  drupal_add_js(libraries_get_path('fancybox') . '/jquery.fancybox-' . GALLERY_LINK_FANCYBOX_VERSION . '.pack.js');
  drupal_add_js(drupal_get_path('module', 'gallery_link') . '/gallery_link.js');

  // We put the $data array into the Drupal.settings.gallery_link.
  drupal_add_js(array('gallery_link' => array($data)), 'setting');

  // We add a an attribute which stores the gallery id ($counter)
  $link_options['attributes']['data-gallery-id'] = $counter;

  // Use default link text when no $link_text was set.
  $link_text = ($link_text) ? $link_text : t('Open gallery');
  // Now we print the link with given $link_text and all given $options
  $output .= l($link_text, '', $link_options);

  $counter++;

  return $output;
}
